baseURL = "https://egghwan.github.io"
[module]
  [module.hugoVersion]
    extended = true
    min = "0.140.0"
  [[module.imports]]
    path = "github.com/gohugoio/hugo-mod-bootstrap-scss/v5"
    disable = false
[params]
  # 다른 설정들...
  [params.docs]
    darkMode = true
    sidebarIcons = true
    titleIcon = true
    navDesc = false
    descriptions = false
    lastMod = true
  
    