baseURL = "https://egghwan.github.io"
[module]
  [module.hugoVersion]
    extended = true
    min = "0.140.0"
  [[module.imports]]
    path = "github.com/gohugoio/hugo-mod-bootstrap-scss/v5"
    disable = false

  # 다른 설정들...
[param]
  [params.docs]
    darkMode = true
    sidebarIcons = true
    titleIcon = true
    navDesc = true
    descriptions = false
    lastMod = true
    prismTheme = "solarized-light"
    intLinkTooltip = true
    [params.footer]
      copyright = "© 2025 egghwan. All contents protected"
[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = false
    noClasses = true  # ⬅️ 꼭 false로! 그래야 테마 CSS가 적용됨
    style = "dracula"     # ⬅️ 스타일 후보: "nord", "dracula", "monokai", "solarized-dark"
    tabWidth = 0
